apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docmost-cert
  namespace: traefik
spec:
  secretName: docmost-cert-tls
  dnsNames:
    - "YOUR_DOMAIN.com"
  issuerRef:
    name: cloudflare
    kind: Issuer
    
