image:
  tag: v3.4.1
    
# redirect all endpoints to https
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true

providers:
  kubernetesCRD:
    # -- Allows IngressRoute to reference resources in namespace other than theirs
    allowCrossNamespace: true

# default ssl cert
tlsStore:
  default:
    defaultCertificate:
      secretName: docmost-cert-tls

# Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    enabled: false

experimental:
  fastProxy: {}

globalArguments:
  - "--global.checknewversion"
  - "--global.sendAnonymousUsage=false"

